// Generated by https://quicktype.io

export interface CharacterResponse {
  code: string;
  message: string;
  data: CharacterData[];
}

export interface CharacterData {
  id: string;
  name: string;
  gender: string;
  ki: string;
  image?: string;
}