// Generated by https://quicktype.io

export interface Hero {
  id: string;
  name: string;
  gender: string;
  ki: string;
  image?: string;
  race?: string;
  originPlanet?: string;
  maxKi?: string;
  description?: string;
  affiliation?: string;
}

export enum Publisher {
  DCComics = "DC Comics",
  MarvelComics = "Marvel Comics",
}
