spring:
  application:
    name: cde-msa-sp-dragon-ball
  header:
    channel: digital
    medium: web
  datasource:
    hikari:
      pool-name: Postgresql
      connectionTimeout: 120000
      validation-timeout: 50000
      idleTimeout: 300000
      maxLifetime: 600000
      minimum-idle: ${DB_MIN_CONNECTIONS:10}
      maximum-pool-size: ${DB_MAX_CONNECTIONS:20}
      leak-detection-threshold: 120000
    url: jdbc:postgresql://${TRANSACTIONAL_POSTGRESQL_HOST:localhost}:${TRANSACTIONAL_POSTGRESQL_PORT:5432}/${TRANSACTIONAL_DATA_BASE_NAME:dragonball}
    username: ${TRANSACTIONAL_POSTGRESQL_USERNAME:cde-msa-dragon-ball}
    password: ${TRANSACTIONAL_POSTGRESQL_PASSWORD:12345678}

management:
  endpoint:
    health:
      show-details: always

configurations:
  max-in-memory-size: ${MAX_IN_MEMORY_SIZE:41943040}
  connect-timeout: ${CONNECT_TIMEOUT:30000}
  read-timeout: ${READ_TIMEOUT:30000}
  services:
    dragon-ball:
      base-path: ${DBZ_BASE_PATH:https://dragonball-api.com}
      all-characters:
        path: ${DBZ_ALL_CHARACTERS_PATH:/api/characters?limit=100}
      specific-character:
        path: ${DBZ_SPECIFIC_CHARACTER_PATH:/api/characters/%s}