// Generated by https://quicktype.io

export interface User {
  code: string;
  message: string;
  data: LoginDataResponse;
}

export interface LoginDataResponse {
  userName: string;
  email: string;
}